/* empty css                      */import{i as c,S as u}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const d=document.getElementById("search-form"),f=document.getElementById("gallery"),i=document.getElementById("loader");let l;d.addEventListener("submit",p);function p(s){s.preventDefault();const o=d.query.value.trim();if(!o){c.error({title:"Error",message:"Please enter a search query."});return}f.innerHTML="",m(o)}async function m(s){i.style.display="block";const t=`https://pixabay.com/api/?key=4687124146871241-4d6b3672e38c39f9ae37ca0de&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const e=await(await fetch(t)).json();if(e.hits.length===0){c.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}),i.style.display="none";return}y(e.hits),l?l.refresh():l=new u(".gallery a",{captionsData:"alt",captionDelay:250})}catch{c.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{i.style.display="none"}}function y(s){const o=s.map(t=>`
      <a href="${t.largeImageURL}" class="gallery-item">
        <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${t.likes}</p>
          <p><b>Views:</b> ${t.views}</p>
          <p><b>Comments:</b> ${t.comments}</p>
          <p><b>Downloads:</b> ${t.downloads}</p>
        </div>
      </a>`).join("");f.insertAdjacentHTML("beforeend",o)}
//# sourceMappingURL=index.js.map
